import type { Metadata } from "next";
import "../globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Providers from "@/Providers/Providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={" antialiased  bg-[#fff3f6]"}>
        <Providers>
          <Toaster position="top-center" duration={1000} richColors />
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
